### ISSUE TITLE
Suggestion for the Prism Test

### ISSUE THREAD

**Issue by Grochek1** [politicaltests/politicaltests.github.io#3]
Hello, I was taking your Prism Test and I think I found a single hiccup.

Several times when I was reading the answers, there were 2 answers which I agreed with, but I could only choose one.

I would suggest make it such that a person can choose either 1 statement to strongly agree with or 1 or 2 statements to somewhat agree with.  

This could likely make it so this test can be more sensetive to people who see some parts of their answer in different answers.

**Comment by politicaltests** [comment]
Hi, the Prism Test was actually not made by me. The section in the website with the Prism Test was exclusively for tests that other people made. The link to the repo can be found here: https://github.com/prismquiz/prismquiz.github.io
